// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serverFund_sys.proto

package serverPlugin

import (
	context "context"
	fmt "fmt"
	tars "github.com/TarsCloud/TarsGo/tars"
	model "github.com/TarsCloud/TarsGo/tars/model"
	requestf "github.com/TarsCloud/TarsGo/tars/protocol/res/requestf"
	current "github.com/TarsCloud/TarsGo/tars/util/current"
	tools "github.com/TarsCloud/TarsGo/tars/util/tools"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CoUserFundRecord_PayType int32

const (
	CoUserFundRecord_WX_PAY         CoUserFundRecord_PayType = 0
	CoUserFundRecord_ALI_PAY        CoUserFundRecord_PayType = 1
	CoUserFundRecord_ANT_CREDIT_PAY CoUserFundRecord_PayType = 2
	CoUserFundRecord_BANK_CARD      CoUserFundRecord_PayType = 3
	CoUserFundRecord_QQ_PAY         CoUserFundRecord_PayType = 4
	CoUserFundRecord_SHOP_BALANCE   CoUserFundRecord_PayType = 5
	CoUserFundRecord_MARK_PAY       CoUserFundRecord_PayType = 6
	CoUserFundRecord_WX_PAY_SELF    CoUserFundRecord_PayType = 7
	CoUserFundRecord_ALI_PAY_SELF   CoUserFundRecord_PayType = 8
)

var CoUserFundRecord_PayType_name = map[int32]string{
	0: "WX_PAY",
	1: "ALI_PAY",
	2: "ANT_CREDIT_PAY",
	3: "BANK_CARD",
	4: "QQ_PAY",
	5: "SHOP_BALANCE",
	6: "MARK_PAY",
	7: "WX_PAY_SELF",
	8: "ALI_PAY_SELF",
}

var CoUserFundRecord_PayType_value = map[string]int32{
	"WX_PAY":         0,
	"ALI_PAY":        1,
	"ANT_CREDIT_PAY": 2,
	"BANK_CARD":      3,
	"QQ_PAY":         4,
	"SHOP_BALANCE":   5,
	"MARK_PAY":       6,
	"WX_PAY_SELF":    7,
	"ALI_PAY_SELF":   8,
}

func (x CoUserFundRecord_PayType) String() string {
	return proto.EnumName(CoUserFundRecord_PayType_name, int32(x))
}

func (CoUserFundRecord_PayType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b756837ae518c6a, []int{4, 0}
}

type ResultEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultEmpty) Reset()         { *m = ResultEmpty{} }
func (m *ResultEmpty) String() string { return proto.CompactTextString(m) }
func (*ResultEmpty) ProtoMessage()    {}
func (*ResultEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b756837ae518c6a, []int{0}
}

func (m *ResultEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultEmpty.Unmarshal(m, b)
}
func (m *ResultEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultEmpty.Marshal(b, m, deterministic)
}
func (m *ResultEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultEmpty.Merge(m, src)
}
func (m *ResultEmpty) XXX_Size() int {
	return xxx_messageInfo_ResultEmpty.Size(m)
}
func (m *ResultEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_ResultEmpty proto.InternalMessageInfo

// TODO: 公共部分  -----------------------------------------------------------
// 分页
type PageInfo struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	OrderKey             string   `protobuf:"bytes,3,opt,name=orderKey,proto3" json:"orderKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageInfo) Reset()         { *m = PageInfo{} }
func (m *PageInfo) String() string { return proto.CompactTextString(m) }
func (*PageInfo) ProtoMessage()    {}
func (*PageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b756837ae518c6a, []int{1}
}

func (m *PageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageInfo.Unmarshal(m, b)
}
func (m *PageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageInfo.Marshal(b, m, deterministic)
}
func (m *PageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageInfo.Merge(m, src)
}
func (m *PageInfo) XXX_Size() int {
	return xxx_messageInfo_PageInfo.Size(m)
}
func (m *PageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PageInfo proto.InternalMessageInfo

func (m *PageInfo) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PageInfo) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PageInfo) GetOrderKey() string {
	if m != nil {
		return m.OrderKey
	}
	return ""
}

// 默认输出
type Result struct {
	Code                 int32             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string            `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Header               map[string]string `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b756837ae518c6a, []int{2}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Result) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Result) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

// ID
type ReqId struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqId) Reset()         { *m = ReqId{} }
func (m *ReqId) String() string { return proto.CompactTextString(m) }
func (*ReqId) ProtoMessage()    {}
func (*ReqId) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b756837ae518c6a, []int{3}
}

func (m *ReqId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqId.Unmarshal(m, b)
}
func (m *ReqId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqId.Marshal(b, m, deterministic)
}
func (m *ReqId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqId.Merge(m, src)
}
func (m *ReqId) XXX_Size() int {
	return xxx_messageInfo_ReqId.Size(m)
}
func (m *ReqId) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqId.DiscardUnknown(m)
}

var xxx_messageInfo_ReqId proto.InternalMessageInfo

func (m *ReqId) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// TODO: 资金流水记录
type CoUserFundRecord struct {
	Id                   int64                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PayType              CoUserFundRecord_PayType `protobuf:"varint,2,opt,name=pay_type,json=payType,proto3,enum=serverPlugin.CoUserFundRecord_PayType" json:"pay_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *CoUserFundRecord) Reset()         { *m = CoUserFundRecord{} }
func (m *CoUserFundRecord) String() string { return proto.CompactTextString(m) }
func (*CoUserFundRecord) ProtoMessage()    {}
func (*CoUserFundRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b756837ae518c6a, []int{4}
}

func (m *CoUserFundRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoUserFundRecord.Unmarshal(m, b)
}
func (m *CoUserFundRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoUserFundRecord.Marshal(b, m, deterministic)
}
func (m *CoUserFundRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoUserFundRecord.Merge(m, src)
}
func (m *CoUserFundRecord) XXX_Size() int {
	return xxx_messageInfo_CoUserFundRecord.Size(m)
}
func (m *CoUserFundRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_CoUserFundRecord.DiscardUnknown(m)
}

var xxx_messageInfo_CoUserFundRecord proto.InternalMessageInfo

func (m *CoUserFundRecord) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CoUserFundRecord) GetPayType() CoUserFundRecord_PayType {
	if m != nil {
		return m.PayType
	}
	return CoUserFundRecord_WX_PAY
}

func init() {
	proto.RegisterEnum("serverPlugin.CoUserFundRecord_PayType", CoUserFundRecord_PayType_name, CoUserFundRecord_PayType_value)
	proto.RegisterType((*ResultEmpty)(nil), "serverPlugin.ResultEmpty")
	proto.RegisterType((*PageInfo)(nil), "serverPlugin.PageInfo")
	proto.RegisterType((*Result)(nil), "serverPlugin.Result")
	proto.RegisterMapType((map[string]string)(nil), "serverPlugin.Result.HeaderEntry")
	proto.RegisterType((*ReqId)(nil), "serverPlugin.ReqId")
	proto.RegisterType((*CoUserFundRecord)(nil), "serverPlugin.CoUserFundRecord")
}

func init() { proto.RegisterFile("serverFund_sys.proto", fileDescriptor_9b756837ae518c6a) }

var fileDescriptor_9b756837ae518c6a = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0xed, 0xda, 0xd8, 0xc0, 0x98, 0x50, 0x6b, 0x14, 0xa9, 0x56, 0x4e, 0x96, 0x0f, 0x15, 0x27,
	0x1f, 0xe8, 0x25, 0xed, 0x6d, 0x43, 0x1c, 0x05, 0x41, 0xa9, 0xb3, 0xd0, 0xaf, 0x93, 0xe5, 0xc4,
	0x5b, 0x8a, 0x4a, 0xb0, 0xbb, 0x6b, 0x22, 0x6d, 0x7f, 0x47, 0xff, 0x4b, 0xff, 0x5c, 0x0f, 0xd5,
	0xee, 0x22, 0x44, 0xdb, 0x93, 0xdf, 0xbc, 0x79, 0xf3, 0xde, 0x78, 0xb4, 0x70, 0x2e, 0xb9, 0x78,
	0xe2, 0xe2, 0x66, 0xbf, 0xab, 0x0a, 0xa9, 0x64, 0xda, 0x88, 0xba, 0xad, 0x71, 0x60, 0xd9, 0x7c,
	0xbb, 0x5f, 0x6f, 0x76, 0xc9, 0x19, 0x04, 0x8c, 0xcb, 0xfd, 0xb6, 0xcd, 0x1e, 0x9b, 0x56, 0x25,
	0x1f, 0xa0, 0x97, 0x97, 0x6b, 0x3e, 0xdd, 0x7d, 0xa9, 0x11, 0xa1, 0xd3, 0x94, 0x6b, 0x1e, 0x91,
	0x98, 0x8c, 0x3c, 0x66, 0x30, 0x5e, 0x40, 0x4f, 0x7f, 0x97, 0x9b, 0x1f, 0x3c, 0x72, 0x0c, 0x7f,
	0xac, 0x75, 0xaf, 0x16, 0x15, 0x17, 0x33, 0xae, 0x22, 0x37, 0x26, 0xa3, 0x3e, 0x3b, 0xd6, 0xc9,
	0x2f, 0x02, 0xbe, 0xcd, 0xd1, 0xb6, 0x0f, 0x75, 0x75, 0xb4, 0xd5, 0x18, 0x43, 0x70, 0x1f, 0xe5,
	0xda, 0x38, 0xf6, 0x99, 0x86, 0x78, 0x09, 0xfe, 0x57, 0x5e, 0x56, 0x5c, 0x44, 0x6e, 0xec, 0x8e,
	0x82, 0x71, 0x9c, 0x9e, 0xae, 0x9d, 0x5a, 0xaf, 0xf4, 0xd6, 0x48, 0xb2, 0x5d, 0x2b, 0x14, 0x3b,
	0xe8, 0xb5, 0xff, 0x7d, 0x5d, 0xa9, 0xa8, 0x13, 0x93, 0xd1, 0x80, 0x19, 0x7c, 0xf1, 0x1a, 0x82,
	0x13, 0xa9, 0x8e, 0xfb, 0xc6, 0x95, 0xd9, 0xa0, 0xcf, 0x34, 0xc4, 0x73, 0xf0, 0x9e, 0xca, 0xed,
	0x9e, 0x1f, 0x56, 0xb0, 0xc5, 0x1b, 0xe7, 0x92, 0x24, 0x2f, 0xc0, 0x63, 0xfc, 0xfb, 0xb4, 0xc2,
	0x21, 0x38, 0x9b, 0xca, 0xcc, 0xb8, 0xcc, 0xd9, 0x54, 0xc9, 0x6f, 0x02, 0xe1, 0xa4, 0x7e, 0x2f,
	0xed, 0x81, 0x19, 0x7f, 0xa8, 0xc5, 0x7f, 0x22, 0xa4, 0xfa, 0x5e, 0xaa, 0x68, 0x55, 0x63, 0xad,
	0x87, 0xe3, 0x97, 0x7f, 0xff, 0xc8, 0xbf, 0x0e, 0x69, 0x5e, 0xaa, 0x95, 0x6a, 0x38, 0xeb, 0x36,
	0x16, 0x24, 0x3f, 0x09, 0x74, 0x0f, 0x24, 0x02, 0xf8, 0x1f, 0x3f, 0x15, 0x39, 0xfd, 0x1c, 0x3e,
	0xc3, 0x00, 0xba, 0x74, 0x3e, 0x35, 0x05, 0x41, 0x84, 0x21, 0x5d, 0xac, 0x8a, 0x09, 0xcb, 0xae,
	0xa7, 0x2b, 0xc3, 0x39, 0x78, 0x06, 0xfd, 0x2b, 0xba, 0x98, 0x15, 0x13, 0xca, 0xae, 0x43, 0x57,
	0xcf, 0xde, 0xdd, 0x99, 0x56, 0x07, 0x43, 0x18, 0x2c, 0x6f, 0xdf, 0xe5, 0xc5, 0x15, 0x9d, 0xd3,
	0xc5, 0x24, 0x0b, 0x3d, 0x1c, 0x40, 0xef, 0x2d, 0x65, 0x33, 0xd3, 0xf7, 0xf1, 0x39, 0x04, 0x36,
	0xa7, 0x58, 0x66, 0xf3, 0x9b, 0xb0, 0xab, 0x07, 0x0e, 0x61, 0x96, 0xe9, 0x8d, 0x3d, 0x70, 0xa5,
	0x92, 0xf7, 0xbe, 0x79, 0x54, 0xaf, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xb3, 0x5b, 0xc2,
	0x6c, 0x02, 0x00, 0x00,
}

// This following code was generated by tarsrpc
// Gernerated from serverFund_sys.proto
type Sys struct {
	s model.Servant
}

//SetServant is required by the servant interface.
func (obj *Sys) SetServant(s model.Servant) {
	obj.s = s
}

//AddServant is required by the servant interface
func (obj *Sys) AddServant(imp impSys, objStr string) {
	tars.AddServant(obj, imp, objStr)
}

////AddServant adds servant  for the service with context
func (obj *Sys) AddServantWithContext(imp impSysWithContext, objStr string) {
	tars.AddServantWithContext(obj, imp, objStr)
}

//TarsSetTimeout is required by the servant interface. t is the timeout in ms.
func (obj *Sys) TarsSetTimeout(t int) {
	obj.s.TarsSetTimeout(t)
}

//TarsSetProtocol is required by the servant interface. t is the protocol.
func (obj *Sys) TarsSetProtocol(p model.Protocol) {
	obj.s.TarsSetProtocol(p)
}

type impSys interface {
}

type impSysWithContext interface {
}

//Dispatch is used to call the user implement of the defined method.
func (obj *Sys) Dispatch(ctx context.Context, val interface{}, req *requestf.RequestPacket, resp *requestf.ResponsePacket, withContext bool) (err error) {
	input := tools.Int8ToByte(req.SBuffer)
	var output []byte
	funcName := req.SFuncName
	switch funcName {

	default:
		return fmt.Errorf("func mismatch")
	}
	var _status map[string]string
	s, ok := current.GetResponseStatus(ctx)
	if ok && s != nil {
		_status = s
	}
	var _context map[string]string
	c, ok := current.GetResponseContext(ctx)
	if ok && c != nil {
		_context = c
	}
	*resp = requestf.ResponsePacket{
		IVersion:     1,
		CPacketType:  0,
		IRequestId:   req.IRequestId,
		IMessageType: 0,
		IRet:         0,
		SBuffer:      tools.ByteToInt8(output),
		Status:       _status,
		SResultDesc:  "",
		Context:      _context,
	}
	return nil
}
