jwt:
  secret: MIICWwIBAAKBgQCraRwunSw1bMXeGL908hnY6mVbWzp2nlIq3o6UKYd+uYcquX0Q\nGQrLU41LLdUYiM6RwNO8X+Z4RZPUWwgmHU5GfYk48u0oBW39qq8RlaMILgVY2PoV\nZeiEHPeL6e0NjYLyGWhPgrDqba8jUrWSjBXvQHhmfYUoBWDk/6jWesnGYQIDAQAB\nAoGASj+JeZeTYsDvJLlLlXiZQaCmrt/hfygtJ2yoDf2/N2Fd71/RkHuIdXKHrZz4\nxVvdPr1r+hkAV/CrjDyyVvAyyxhEzGu2GTlSxRKuu59vP+UQVK2ssc5DOnouwcj3\n3owQo+ZWczcyqjyerC5dHeLN6yDdE/OBRq3rM7lAVgG4xAECQQDbER96fxgmHmwH\nx8FWmezwGhE57Ava2EC7PEHCZngZokFbbAnU/7Z9vm+cbyaHcLsiqoWa9H9hPSv/\n28B4besxAkEAyE8m66fpkcsFMlNvbbjs4xa69ctq8iWTKMytLGFl+6iQNvwBc8fF\nT+sjxu2vAPfBBeMLjWzR6hC78/gXCWdiMQJAGwgu4TfDrBh+7irZEa2mzi35SDN3\ndwbOXgxedPWeBlO+SuC3CeCQDU4tiZkxoO7pOKrgF7Hp8f7Rah4czv+JUQJAKFz6\nxMXDJSO52lhBveRjp6bu6ZSh6kV0D+aehrDhsgJXfRzu1fvNYLtLLEy81P8XoC4O\nJ+NjsTzKAvFdAwIYIQJANcXbQytDxQSQDf81ouovW0vXdk0USH/gWhB1w9bIReNF\nTB+r9XOMCG8a6cK9QVseJjoEXA/lG+cP2vWbmkZ+PQ==
  timeout: 3600

log:
  remote: true
  hour: 0

redis:
  addr: 192.168.2.22:6379
  password: 123456
  db: 0
  pool_size: 5
  min_idle_conns: 200

application:
  domain: localhost:800011
  ishttps: false
  mode: dev
  readtimeout: 1
  writertimeout: 2
sessions:
  name: golang_sessionid
  key: YGJBI!H#E%&GDIBKHj!lj(*eft&*&fiUyt2937rgi_)(*!#U04hroejl
  domain: # localhost 不需要设置
  addr: 192.168.2.22:6379
  password: 123456
  db: 14
  pool_size: 5
  min_idle_conns: 200
ssl:
  key: keystring
  pem: temp/pem.pem
email:
  username: xxx@163.com # 国内建议使用163邮箱, 到达率高, 且基本不会被其他邮件服务识别为垃圾邮件
  password: password # 邮箱密码
  host: smtp.163.com # 邮件服务商 smtp 地址
  port: 465 # 端口
  ssl: true # 是否启动ssl
kafka:
  bootstrap.servers: localhost
  group.id: default
  auto.offset.reset: earliest