log:
  remote: true
  hour: 0

redis:
  addr: 192.168.31.114:6379
  password: 123456
  db: 0
  pool_size: 5
  min_idle_conns: 200
mongo:
  url: mongodb://192.168.31.114:27017
  database: mall_shop
  max_conn_idle_time: 180
  max_pool_size: 2
  username: admin
  password: 123456
database:
  master:
    addr: 192.168.31.114:3306
    dbname: mall_shop
    username: root
    password: 123456
    max_idle: 100
    max_open: 100
  slave:
    -
      addr: 192.168.31.114:3306
      dbname: mall_shop
      username: root
      password: 123456
      max_idle: 100
      max_open: 100
sessions:
  name: golang_sessionid
  key: YGJBI!H#E%&GDIBKHj!lj(*eft&*&fiUyt2937rgi_)(*!#U04hroejl
  domain: # localhost 不需要设置
  addr: 192.168.2.22:6379
  password: 123456
  db: 14
  pool_size: 5
  min_idle_conns: 200
ssl:
  key: keystring
  pem: temp/pem.pem
email:
  username: xxx@163.com # 国内建议使用163邮箱, 到达率高, 且基本不会被其他邮件服务识别为垃圾邮件
  password: password # 邮箱密码
  host: smtp.163.com # 邮件服务商 smtp 地址
  port: 465 # 端口
  ssl: true # 是否启动ssl
kafka:
  bootstrap.servers: localhost
  group.id: default
  auto.offset.reset: earliest